asoc: samsung: Fix compilation break in Samsung's PCM driver
The PCM driver broke because of the move to generic DMA APIs which
re-defined the "struct s3c2410_dma_client" in dma-pl330.h. Fix the
following build break by including the machine specific dma header.

arch/arm/plat-samsung/include/plat/dma-pl330.h:106:8: error: redefinition
of ‘struct s3c2410_dma_client’
arch/arm/plat-samsung/include/plat/dma.h:40:8: note: originally defined here

BUG=chrome-os-partner:9694
TEST=build tested

Change-Id: I921c7f4201764eda9497d890875b76da4abb6e2f
Signed-off-by: Abhilash Kesavan <a.kesavan@samsung.com>
Reviewed-on: https://gerrit-int.chromium.org/17829
Reviewed-by: Olof Johansson <olofj@google.com>
Tested-by: Olof Johansson <olofj@google.com>
Commit-Ready: Olof Johansson <olofj@google.com>