arm64: vexpress: Select ARCH_REQUIRE_GPIOLIB for PLAT_VEXPRESS
Patch 25c92a37a (arm64: Always select ARM_AMBA and GENERIC_GPIO)
expects platforms to have GPIO so we need to make sure vexpress
always has this by selecting ARCH_REQUIRE_GPIOLIB.

Without this change drivers like MMC fail to compile due to missing
gpio definitions like:

In file included from include/linux/gpio.h:48:0,
                 from drivers/mmc/core/slot-gpio.c:12:
include/asm-generic/gpio.h: In function 'gpio_get_value_cansleep':
include/asm-generic/gpio.h:235:2: error: implicit declaration of function '__gpio_get_value'

Signed-off-by: Jon Medhurst <tixy@linaro.org>