mod/file2alias: Fix build failures introduced by commit 6543becf
Commit 6543becf (mod/file2alias: make modalias generation safe for
cross compiling) causes occasional build errors like:

  In file included from include/linux/types.h:5:0,
                   from include/linux/mod_devicetable.h:11,
                   from scripts/mod/devicetable-offsets.c:2:
  include/uapi/linux/types.h:4:23: fatal error: asm/types.h: No such file or directory

because with parallel make it is racing with the generation of
asm/types.h by scripts/Makefile.asm-generic.

This patch to fix the problem was...
Suggested-by: Andreas Schwab <schwab@linux-m68k.org>
Signed-off-by: Jon Medhurst <tixy@linaro.org>