video: Make vexpress DVI driver depend on CONFIG_FB
The driver uses symbols from fbmem.c so if CONFIG_FB is not
selected we get build errors like:

drivers/built-in.o: In function `vexpress_dvi_fb_select':
 :(.text+0x1b6c): undefined reference to `lock_fb_info'
 :(.text+0x1ba0): undefined reference to `registered_fb'

Note, this is only a partial solution because we still have a
problem if CONFIG_FB is selected as a module.

Signed-off-by: Jon Medhurst <tixy@linaro.org>