Revert "mod/file2alias: make modalias generation safe for cross compiling"
This reverts commit 6543becf26fff612cdadeed7250ccc8d49f67f27.

I believe this is causing errors like:

  In file included from include/linux/types.h:5:0,
                   from include/linux/mod_devicetable.h:11,
                   from scripts/mod/devicetable-offsets.c:2:
  include/uapi/linux/types.h:4:23: fatal error: asm/types.h: No such file or directory

because with parallel make it is racing with the generation of
asm/types.h by scripts/Makefile.asm-generic.