Revert "mod/file2alias: make modalias generation safe for cross compiling"
This reverts commit 6543becf26fff612cdadeed7250ccc8d49f67f27.

Looks like the above commit introduces a parallel make race causing
"include/uapi/linux/types.h:4:23: fatal error: asm/types.h: No such
file or directory" when compilin scripts/mod/devicetable-offsets.s

Signed-off-by: Andrey Konovalov <andrey.konovalov@linaro.org>