UPSTREAM: staging/gdm72xx: coding style fixes gdm_qos.c
following warnings were fixed

drivers/staging/gdm72xx/gdm_qos.c:198: ERROR: "foo* bar" should be "foo *bar"
drivers/staging/gdm72xx/gdm_qos.c:198: ERROR: "foo* bar" should be "foo *bar"
drivers/staging/gdm72xx/gdm_qos.c:244: WARNING: quoted string split across lines

Signed-off-by: Devendra Naga <devendra.aaru@gmail.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 9b90b712c9504d36e60eaefce0baf66d64b3c901)

Change-Id: I76ab57e06e3773c2d595bac5ed468e72fac26838
Signed-off-by: Ben Chan <benchan@chromium.org>
Reviewed-on: https://gerrit.chromium.org/gerrit/28220
Reviewed-by: Olof Johansson <olofj@chromium.org>