ARM: SAMSUNG: Fix compilation error with ldr instruction
ldr r2,[ \r3, #(VALUE) ] changed to ldr r2,[\r3, #(VALUE) ] ,
removed extra space after the brace to resolve compilation error.

Fixes following error.
arch/arm/kernel/debug.S: Assembler messages:
arch/arm/kernel/debug.S:83: Error: ARM register expected -- `ldr r2,[ r3,#(0x08)]'
arch/arm/kernel/debug.S:83: Error: ARM register expected -- `ldr r2,[ r3,#(0x18)]'
arch/arm/kernel/debug.S:83: Error: ARM register expected -- `ldr r2,[ r3,#(0x10)]'
arch/arm/kernel/debug.S:85: Error: ARM register expected -- `ldr r2,[ r3,#(0x08)]'
arch/arm/kernel/debug.S:85: Error: ARM register expected -- `ldr r2,[ r3,#(0x18)]'
arch/arm/kernel/debug.S:85: Error: ARM register expected -- `ldr r2,[ r3,#(0x10)]'

Signed-off-by: Fahad Kunnathadi <fahad.k@linaro.org>
Signed-off-by: Tushar Behera <tushar.behera@linaro.org>